version: '3.8'

services:
  database:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fuarza_ventas
    ports:
      - "5432:5432"
    volumes:
      - /postgres-data-force:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@jeff.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database

volumes: 
   postgres-data-force:
     #external: trueversion: '3.8'




